### ISSUE TITLE
responsive issues

### ISSUE THREAD

**Issue by disko998** [GavriloStankovic/Extract-Craft#1]

**Comment by disko998** [comment]
- [x] probati da ubacis container na svakoj sekciji i izbaci margin 8%...
- [x] industryLeader prosiriti text na prvom brake pointu
- [x] industryLeader  smanjiti sliku takodje
- [x] sve ispod 600px ide na mobile velicine u figmi
- [x] concentration odradi brake point ranije
- [x] napravi globval class za primary button `.primary-button`
- [x] double click na accourdition zatvara
- [x] sredi malo boolje footer za manje velicine
- [x] ograniciti buttoon za desktop na 77px max-height

**Comment by disko998** [comment]
@GavriloStankovic `allowZeroExpanded : boolean [optional, default: false]` prop na  Accordion ce ti resiti problem

**Comment by disko998** [comment]
- [x] Dodaj media query za container kad je ispod 1360px (kad navbar predje u mobile menu) da pedding sa strane bude 40px umesto 160px.
- [x] Vidim da si imao problem sa backgrund image u containeru pa nisi stavljao container na neke sekcije i onda ti se gubi pedding sa strane tako da to moras resiti. Kako mozes resiti problem umesto sto ti je trenutno layout:
```html 
<div class='container industry-wrapper'>
  <div class='industry-leader'>
   ...
  </div>
</div>
```
Treba da uradis ovo:
```html 
<div class='industry-wrapper'>
  <div class='container'>
   <div class='industry-leader'>
     ...
    </div>
  </div>
</div>
```
Znaci prvo ide sekcija koja je `width=100%` i bez ikakvih peddinga na koju stavljas sliku tak da uvek bude od ivice do ivice i menjas je po potrebi za responsive, a unutar sekcija ide container pa onda content.

- [x] Sredi malo ovu skeciju da budu jednake duzine uvek
![Screenshot 2023-06-09 210938](https://github.com/GavriloStankovic/Extract-Craft/assets/45342884/11738f70-8612-406f-826f-2726ec475187)

- [x] ovo takodje
![Screenshot 2023-06-09 211438](https://github.com/GavriloStankovic/Extract-Craft/assets/45342884/7251e796-ba82-4a61-8c53-97e91b5ce125)

- [x] Dodati jednostavnu hover tranziciju na buttons, mozda da bude fill sa tom istom bojom `backgroound: green` a text `color: white` i takodje mozes smisliti neki effekat za menu links. Obavezno na oba staviti `cursor: pointer`

**Comment by GavriloStankovic** [comment]
Trebalo bi da je sredjeno, acordion se zatvara, container je dodat i sve umesto 160px paddinga kada dodje na 1360px ide na 40px padding, izgleda dosta bolje. Duzine su sredjene, vise ne strce, samo kada tekst krene da se lomi visine im nisu iste, ne znam kojom opcijom bih konstantno drzao gornju ivicu da nikada ne propada. Sredjen je i footer, ovaj deo vise BUY ONLINE ne ispada, sve se srazmerno siri i smanjuje, dodati su haveri na svu dugmad, nekima se menja pozadina, nekima ne. Ali svi imaju cursor: pointer, svi imaju mali scale lepse izgleda, skroz gore u navigacionom meniju sam dodao malu animaciju kada se prelazi misem preko da linija seta, i kada prelazis preko kartica, ovih sto idu po 3 u nizu imaju mali translate, izgleda malo lepse i nije napadno.

**Comment by disko998** [comment]
Dobro je mozemo otvoriti PR (pull request) probaj sam da se snadjes kako se to radi i dodaj me kao reviwer pa cu sutra da pogledam kod! @GavriloStankovic
