### ISSUE TITLE
Mobile nav menu 

### ISSUE THREAD

**Issue by disko998** [GavriloStankovic/Extract-Craft#3]

**Comment by disko998** [comment]
Napraviti menu drawer za mobile i tablet, za ovo nemamo trenutno dizajn pa ces morati da improviziras malo ali cu ti dati primer kako bi trebalo da izgleda: https://www.figma.com/file/kQLd2pbx3QNGyYNkGqkIbl/Kasia-Studio?type=design&node-id=135-1538&t=qRa93uQqDuXDGIBX-0

Naravno nemoj da pratis skroz ovaj dizajn samo primer kako da postavis layout znaci ovo su kriterijumi:

- [x] Menu izlazi sa desne strane i prekriva ceo ekran na mobile dok na tabletu bi isko mozda do 2/3 ekrana vidi kako izgleda bolje.
- [x] Jednostavna slide in tranzicija, napraviti custom sa sass.
- [x] U meniju sa gore u headeru staviti logo levo i desno X button koji zatvara meni kao sto je na figmi.
- [x] Ispod se nalaze linkovi jedan ispod drugog ovde ne treba pratiti figmin dizajn samo layout, sto se tice dizajna tu mozes proizvoljno da bude samo text a ne button kao na figmi.
- [x] linkovi su ona 4 koja se nalaze u navbaru.

**Comment by disko998** [comment]
@GavriloStankovic

**Comment by GavriloStankovic** [comment]
Zavrsio sam za mobile, posto sam se malko igrao sa pozadinom, lepse bi bilo da i tablet bude cela velicina ekrana jer mi se onda vidi mala razlika izmedju dve pozadine. A mislim da je estetski dosta lepo za nekoga ko nije mnogo talentovan za dizajn, tako da bih i na tablet i na mobile velicinu stavio da menu bude ceo ekran, jer mnogo lepse izgleda.
